[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000

[font]
size = 16.0

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[colors.primary]
background = "#181825"
foreground = "#CAD3F5"

[colors.normal]
black   = "#161622"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#F5C2E7"
cyan    = "#94E2D5"
white   = "#3F3752"

[window]
opacity = 1

[window.padding]
x = 15
y = 15

[[keyboard.bindings]]
chars = "\u0002\u0022"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002%"
key = "H"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00020"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Control"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002c"
key = "\\"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002x"
key = "Q"
mods = "Control"
