[font]
size = 16.0

[colors.primary]
background = "#181825"
foreground = "#CAD3F5"   # adjust if you want something from the image

[colors.normal]
black   = "#161622"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#F5C2E7"
cyan    = "#94E2D5"
white   = "#3F3752"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15
